# Generated by Django 5.2.9 on 2025-12-04 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_orcamento_itens_itemorcamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='imagens',
        ),
        migrations.CreateModel(
            name='ImagemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='orcamento_imagens/')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='core.orcamento')),
            ],
        ),
    ]
